### ISSUE TITLE
import Image ImportError: No module named Image

### ISSUE THREAD

**Issue by dixon1e** [ankitaggarwal011/PyCNN#2]
When using pillow on Mac OS X Yosemite this error occurs. Solution is to change in cnnimg.py

```
import Image as img
```

to

```
from PIL import Image as img
```

**Comment by ankitaggarwal011** [comment]
Thanks a lot for reporting the issue. I appreciate it.

I'm aware that the Image library is no longer supported and is incompatible with Python 3. Pillow is an obvious replacement and its in the pipeline. However, I'm unable to get time to change the library from Image to Pillow. This would require updated import instructions and whether its consistent with the earlier usage of Image library. This is in the pipeline, however, if you're interested in the updating this library from Image to PIL, I would really appreciate. Please let me know. Thanks again.

**Comment by dixon1e** [comment]
Hi Ankit,

Thank you for reaching out. I posted the issue mainly to have a placeholder
for the error. Hopefully Mac users will see this and get a quick fix as
they try the code.

My main interest is processing images and finding objects, currently a
place where Convolutional NN's are big. I'll check back in with you if I
get time to work on this.

dcd

**Comment by ankitaggarwal011** [comment]
Thanks for your response. I understand. 

It's true that convolutional neural networks are known to work well for object recognition, however, I hope you are aware that the library is about cellular neural networks (CNN) which are different from convolutional neural networks (ConvNet). Thanks.

**Comment by dixon1e** [comment]
Hi Ankit,

Absolutely aware, but thanks for checking, as I admit I was quite confused
at first. The speed of the Cellular networks looks really fast and that's
quite the problem to solve for Convo's. The fact that chips exist is even
more interesting. Your post and repo are very well appreciated and I hope
to be able to contribute.

dcd

**Comment by ankitaggarwal011** [comment]
Yeah, I know it could be confusing :)

Originally ConvNet acronym was used for convolutional neural networks, however, some people prefer using CNN, which can lead to confusion at times. Thank you for your feedback. I appreciate it. I hope the library would be useful to you.

**Comment by Sai-Adarsh** [comment]
try:
    from PIL import Image
except ImportError:
    import Image

**Comment by ankitaggarwal011** [comment]
@Sai-Adarsh Thanks, but this was already resolved.

**Comment by snjjay** [comment]
It occurs as a result of the PIL library's degradation. Instead, you should instal and use the pillow library's replacement to address the problem. I am aware that the Image library is deprecated and incompatible with Python 3. Pillow is a natural successor, and it's on the way.  I find this link helpful
https://kodlogs.net/331/importerror-no-module-named-image/
