### ISSUE TITLE
Add suitable docstrings to the module, classes and functions

### ISSUE THREAD

**Issue by ankitaggarwal011** [ankitaggarwal011/PyCNN#27]
Please refer these links while constructing the suitable docstrings.
- https://www.python.org/dev/peps/pep-0257/
- http://stackoverflow.com/questions/2557110/what-to-put-in-a-python-module-docstring
- http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

Any suggestions are welcome. Thanks.

**Comment by lostwarrior404** [comment]
I'll try to work on this.Can you please explain the purpose/use of the function `f(..)` and `cnn(..)` in`pycnn.py`.

**Comment by ankitaggarwal011** [comment]
Thanks @lostwarrior404. I appreciate your help. 

> cnn function is the approximate sigmoidal kernel function for this neural network.
> 
> f(x, t, ...) computes the derivative of x at t.

**Comment by iraquitan** [comment]
Adde [PR#30](https://github.com/ankitaggarwal011/PyCNN/pull/30) for this issue.

**Comment by ankitaggarwal011** [comment]
Excellent work @iraquitan, but @lostwarrior404 mentioned that he is working on this issue. I hope he didn't start working on it. 
In the future, please comment on the issue that your working on to avoid any duplication. Thank you for your contribution.

@lostwarrior404, shall we go ahead with this? I hope you didn't start working on this yet.

**Comment by lostwarrior404** [comment]
Please go ahead with it.Open source software is about community not about a single person.And @iraquitan has done a much better job than me.

**Comment by ankitaggarwal011** [comment]
@lostwarrior404, thanks for your good open source spirit. 
Your contribution is appreciated. @iraquitan, please go ahead with this issue.

**Comment by iraquitan** [comment]
Ok, I should've commented here before working. I'll do that next time. Thanks for comprehension @lostwarrior404 and @ankitaggarwal011.
