### ISSUE TITLE
Use PyCNN to do binary classification

### ISSUE THREAD

**Issue by alianoroozi** [ankitaggarwal011/PyCNN#45]
Hi. I want to thank you for the code. I have a question, though. Can PyCNN be used for binary classification of numerical data?

**Comment by ankitaggarwal011** [comment]
Hey @alianoroozi, not directly. PyCNN is designed for image processing. In order to do classification of numerical data, you would need something like this https://ieeexplore.ieee.org/document/7926973.

**Comment by shifaniadriani** [comment]
Hi. Thank you for the code. I have a question. Can PyCNN be used for images classification? thank you.
