### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by ankitaggarwal011** [ankitaggarwal011/PyCNN#8]
Adding unit tests for each part of the library, especially the image processing functions and the core library functions would enable easy debugging and extension of library. This is important as it ensures that a new functionality or improvement doesn't affect the other parts inadvertently. 

Any suggestions are welcome. Thanks!

**Comment by LLluma** [comment]
There is pull request #13 .
Tests are running on Travis CI.

**Comment by ankitaggarwal011** [comment]
@LLluma, I've merged your request and setup Travis CI, the first unit test is successfully added. Please consider adding more tests. Thank you.
